### ISSUE TITLE
The projects listed are freely modifiable on the website

### ISSUE THREAD

**Issue by masnun** [braveclojure/open-source-projects#1]
For example, I could visit this link - http://open-source.braveclojure.com/projects/clj-rethinkdb/edit and add this line - "I love Clojure!" to it. 

Is this supposed to happen? I can see one issue with this - malicious people can deliberately alter project descriptions on the site. May be they have to login using Github? Or there needs to be some sort of authentication there.

**Comment by flyingmachine** [comment]
This is a good point, and I think it’s OK for now. If it starts to be an issue I’ll add authentication. Luckily, it’s all backed by git so it’s easy to roll back changes.

**Comment by masnun** [comment]
Thanks for the prompt response. I just wanted to make sure you're aware of the issue. 

I agree with the approach. I think we can close the issue.
